apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "goircd.fullname" . }}
  labels:
    app: {{ template "goircd.name" . }}
    chart: {{ template "goircd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "goircd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "goircd.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "goircd.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -motd
            - /config/MOTD
          envFrom:
            - configMapRef:
                name: {{ template "goircd.fullname" . }}
          volumeMounts:
            - name: config
              mountPath: /config
          ports:
            - name: irc
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.image.healthcheckPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: health
          readinessProbe:
            httpGet:
              path: /ready
              port: health
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
