apiVersion: v1
kind: Service
metadata:
  name: {{ template "goircd.fullname" . }}
  labels:
    app: {{ template "goircd.name" . }}
    chart: {{ template "goircd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: irc
      protocol: TCP
      name: irc
  selector:
    app: {{ template "goircd.name" . }}
    release: {{ .Release.Name }}
